name: orthanc # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.5.6' # just for humans, typically '1.2+git' or '1.3.2'
summary: Lightweight DICOM server for healthcare and medical research.
description: |
  Orthanc aims at providing a simple, yet powerful standalone DICOM server. 
  It is designed to improve the DICOM flows in hospitals and to support 
  research about the automated analysis of medical images. Orthanc lets 
  its users focus on the content of the DICOM files, hiding the complexity 
  of the DICOM format and of the DICOM protocol

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  orthanc:
    command: sbin/Orthanc
    daemon: simple
    plugs:
      - home
      - network
      - network-bind
      
  orthancrecovercompressedfile:
    command: OrthancRecoverCompressedFile


parts:
  orthanc:
    plugin: cmake
    source: https://bitbucket.org/sjodogne/orthanc/src
    source-type: hg
    source-branch: default
    configflags:  
      - "-DSTATIC_BUILD=ON"
      - "-DCMAKE_BUILD_TYPE=Release"
    build-packages:
      - "build-essential"
      - "unzip"
      - "mercurial"
      - "uuid-dev"
      - "libcurl4-openssl-dev"
      - "liblua5.1-0-dev"
      - "libgtest-dev"
      - "libpng-dev"
      - "libsqlite3-dev"
      - "libssl-dev"
      - "libjpeg-dev"
      - "zlib1g-dev"
      - "libdcmtk2-dev"
      - "libboost-all-dev"
      - "libwrap0-dev"
      - "libcharls-dev"
      - "libjsoncpp-dev"
      - "libpugixml-dev"
      - "doxygen"
      
  orthanc-webviewer:
    plugin: cmake
    source: https://bitbucket.org/sjodogne/orthanc-webviewer/src
    source-type: hg
    source-branch: default
    configflags:
      - "-DSTATIC_BUILD=ON"
      - "-DCMAKE_BUILD_TYPE=Release"
  
  orthanc-databases-postgresql:
    plugin: cmake
    source: https://bitbucket.org/sjodogne/orthanc-databases/src/default/PostgreSQL/
    source-type: hg
    source-branch: default
    source-subdir: PostgreSQL
    configflags:
      - "-DSTATIC_BUILD=ON"
      - "-DCMAKE_BUILD_TYPE=Release"

  orthanc-databases-mysql:
    plugin: cmake
    source: https://bitbucket.org/sjodogne/orthanc-databases/src/default/PostgreSQL/
    source-type: hg
    source-branch: default
    source-subdir: MySQL
    configflags:
      - "-DSTATIC_BUILD=ON"
      - "-DCMAKE_BUILD_TYPE=Release"

  orthanc-transfers:
    plugin: cmake
    source: https://bitbucket.org/sjodogne/orthanc-transfers/src
    source-type: hg
    source-branch: default
    configflags:
      - "-DSTATIC_BUILD=ON"
      - "-DCMAKE_BUILD_TYPE=Release"

  orthanc-dicomweb:
    plugin: cmake
    source: https://bitbucket.org/sjodogne/orthanc-dicomweb/src
    source-type: hg
    source-branch: default
    configflags: 
      - "-DSTATIC_BUILD=ON"
      - "-DCMAKE_BUILD_TYPE=Release"

  orthanc-authorization:
    plugin: cmake
    source: https://bitbucket.org/osimis/orthanc-authorization/src
    source-type: hg
    source-branch: default
    configflags: 
      - "-DSTATIC_BUILD=ON"
      - "-DCMAKE_BUILD_TYPE=Release"




